import { DirectoryTypes } from "./directory";
export const UI_URLS = {
  HOME: "/",
  ACTIVITY: "/activity",
  CONTROL: "/control",
  CONTROLS: "/controls",
  DIRECTORIES: "/directories",
  DIRECTORY: "/directory/:id/:type?",
  HELP: "/help",
  LOGIN: "/login",
  LOGOUT: "/logout",
  NEWS: "/news",
  OVERVIEW: "/overview",
  PERMISSION: "/permission",
  PERMISSIONS: "/permissions",
  POLICIES: "/policies",
  POLICIES_VALUES: "/policies/values",
  POLICIES_SETTINGS: "/policies/settings",
  POLICY: "/policy",
  PROFILE: "/profile",
  PROFILE_ACCOUNT: "/profile/account",
  PROFILE_KEYS: "/profile/keys",
  PROFILE_ACCESS_KEYS: "/profile/access-keys",
  PROFILE_SSH_KEYS: "/profile/ssh-keys",
  REPORTS: "/reports",
  RESOURCE: "/resource",
  RESOURCES: "/resources",
  // FIXME: can be removed after fully migrate to smart folders
  RESOURCE_GROUPS: "/resource-groups",
  SMART_FOLDERS: "/smart-folders",
  SMART_FOLDER: "/smart-folder/:id",
  SEARCH: "/search",
  TASKS: "/tasks"
};
